services:
  c-client:
    environment:
      - MQTT_PORT=${MQTT_TLS_EXT_PORT}
    container_name: ${TAG}-C-client
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /d/작업/프로그램 개발/IoT-Security-Architecture-Configure/infra/infra-c-client-device:/app
    tty: true 
    stdin_open: true

# CI/CD test 26.03.14 0532