services:
  c-client:
    environment:
      - MQTT_PORT=${MQTT_TLS_EXT_PORT}
    container_name: ${TAG}-C-client
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    tty: true 
    stdin_open: true

#CI/CD Dev test 26.03.12 0559