services:
  # 1. SSH (Bastion Host)
  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: ssh
    environment:
      - USER_NAME=${SSH_USER}
      - PUBLIC_KEY_FILE=/pubkey/A-KEY.pub
      - SUDO_ACCESS=false
    ports:
      - "${SSH_EXT_PORT}:2222"
    volumes:
      - ./ssh-key/A-KEY.pub:/pubkey/A-KEY.pub:ro
      - ../Infra-server/mosquitto/docker-entrypoint.sh:/mosquitto/docker-entrypoint.sh:ro
      - ../Infra-server/mosquitto/log:/mosquitto/log:ro
      - ../Infra-server/backend:/backend:ro
      - /var/run/docker.sock:/var/run/docker.sock  # 컨테이너 제어용
    networks:
      - service-net   # 서비스 서버 접근
      - mgmt-net     # 인프라 서버 접근

networks:
  mgmt-net:
    external: true
    name: deploy_mgmt-net
  service-net:
    external: true
    name: infra-server_service-net