services:
  # 1. SSH (Bastion Host)
  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: ${TAG}-ssh
    environment:
      - USER_NAME=${SSH_USER}
      - PUBLIC_KEY_FILE=/pubkey/1-LEVEL-KEY.pub
      - SUDO_ACCESS=false
    ports:
      - "${SSH_EXT_PORT}:2222"
    volumes:
      - ./ssh-key/1-LEVEL-KEY.pub:/pubkey/1-LEVEL-KEY.pub:ro
      - ./mosquitto/docker-entrypoint.sh:/mosquitto/docker-entrypoint.sh:ro
      - ./mosquitto/log:/mosquitto/log:ro
      - ./backend:/backend:ro
      - /var/run/docker.sock:/var/run/docker.sock  # 컨테이너 제어용
    networks:
      - service-net   # 서비스 서버 접근
      - mgmt-net     # 인프라 서버 접근

  # 2. CD Server
  cd-server:
    build: ./CD-server
    container_name: ${TAG}-cd-server
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
    #  - DOCKER_CONTEXT=default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 제어용
      - ~/.docker/config.json:/root/.docker/config.json
      - ./:/infra-server                            # docker-compose.yml 접근
    networks:
      - service-net   # 서비스 서버 배포용
      - mgmt-net     # Discord Bot과 통신

  # 3. Discord Bot
  discord-bot:
    build: ./discord-bot
    container_name: ${TAG}-discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - CD_SERVER_URL=http://${TAG}-cd-server:3000
      - CD_DEV_SERVER_URL=http://${TAG}-cd-dev-server:3000
    networks:
      - mgmt-net

networks:
  mgmt-net:
    driver: bridge